import type { Metadata } from 'next'
import { Rubik , Roboto  } from 'next/font/google'
import './globals.css'

const rubik = Rubik({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-rubik",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: 'FinanceX',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} ${roboto.variable} `}>{children}</body>
    </html>
  )
}
